//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("NLog.Xml")]
[assembly: AssemblyCompany("LoreSoft")]
[assembly: AssemblyCopyright("Copyright © 2013 LoreSoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("2.1.0.0")]
[assembly: AssemblyFileVersion("2.1.0.0")]
[assembly: AssemblyInformationalVersion("2.1.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "NLog.Xml";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2013 LoreSoft";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "2.1.0.0";
    
    internal const string AssemblyFileVersion = "2.1.0.0";
    
    internal const string AssemblyInformationalVersion = "2.1.0.0";
    
    private ThisAssembly() {
    }
}
